export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      patients: {
        Row: {
          id: string
          full_name: string
          birth_date: string
          estimated_due_date: string
          current_gestational_age_weeks: number
          current_gestational_age_days: number
          registration_date: string
          registration_gestational_age_weeks: number
          registration_gestational_age_days: number
          preferred_delivery_type: string
          obstetrician_id: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          baby_name?: string
          partner_name?: string
          phone: string
          zip_code: string
          street?: string
          neighborhood?: string
          city?: string
          state?: string
          is_born: boolean
          birth_preparation_course: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy: string
          breastfeeding_workshop: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring: string
          is_removed: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          birth_date: string
          estimated_due_date: string
          current_gestational_age_weeks: number
          current_gestational_age_days: number
          registration_date: string
          registration_gestational_age_weeks: number
          registration_gestational_age_days: number
          preferred_delivery_type: string
          obstetrician_id: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          baby_name?: string
          partner_name?: string
          phone: string
          zip_code: string
          street?: string
          neighborhood?: string
          city?: string
          state?: string
          is_born?: boolean
          birth_preparation_course?: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course?: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy?: string
          breastfeeding_workshop?: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation?: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring?: string
          is_removed?: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          birth_date?: string
          estimated_due_date?: string
          current_gestational_age_weeks?: number
          current_gestational_age_days?: number
          registration_date?: string
          registration_gestational_age_weeks?: number
          registration_gestational_age_days?: number
          preferred_delivery_type?: string
          obstetrician_id?: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          baby_name?: string
          partner_name?: string
          phone?: string
          zip_code?: string
          street?: string
          neighborhood?: string
          city?: string
          state?: string
          is_born?: boolean
          birth_preparation_course?: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course?: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy?: string
          breastfeeding_workshop?: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation?: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring?: string
          is_removed?: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          created_at?: string
          updated_at?: string
        }
      }
      user_types: {
        Row: {
          id: string
          name: string
          display_name: string
          description?: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          display_name: string
          description?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          display_name?: string
          description?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          full_name: string
          display_name?: string
          username?: string
          password_hash?: string
          user_type: string
          is_admin: boolean
          is_superuser: boolean
          has_admin_power: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          full_name: string
          display_name?: string
          username?: string
          password_hash?: string
          user_type: string
          is_admin?: boolean
          is_superuser?: boolean
          has_admin_power?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          display_name?: string
          username?: string
          password_hash?: string
          user_type?: string
          is_admin?: boolean
          is_superuser?: boolean
          has_admin_power?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      patient_history: {
        Row: {
          id: string
          patient_id: string
          user_id: string
          action_type: string
          changed_fields: Json
          old_values: Json
          new_values: Json
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          user_id: string
          action_type: string
          changed_fields: Json
          old_values?: Json
          new_values?: Json
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          user_id?: string
          action_type?: string
          changed_fields?: Json
          old_values?: Json
          new_values?: Json
          created_at?: string
        }
      }
      born_patients: {
        Row: {
          id: string
          patient_id: string
          birth_date: string
          delivery_type: string
          maternity: string
          maternity_id?: string
          baby_name: string
          baby_gender?: string
          birth_gestational_age_weeks: number
          birth_gestational_age_days: number
          full_name: string
          patient_birth_date: string
          estimated_due_date: string
          registration_date: string
          registration_gestational_age_weeks: number
          registration_gestational_age_days: number
          preferred_delivery_type: string
          obstetrician_id: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          doula_present_id?: string
          obstetric_nurse_present_id?: string
          birth_observations?: string
          birth_preparation_course: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy: string
          breastfeeding_workshop: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring: string
          mother_age_at_birth?: number
          is_removed: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          removal_gestational_age_weeks?: number
          removal_gestational_age_days?: number
          created_by?: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          birth_date: string
          delivery_type: string
          maternity: string
          maternity_id?: string
          baby_name: string
          baby_gender?: string
          birth_gestational_age_weeks: number
          birth_gestational_age_days: number
          full_name: string
          patient_birth_date: string
          estimated_due_date: string
          registration_date: string
          registration_gestational_age_weeks: number
          registration_gestational_age_days: number
          preferred_delivery_type: string
          obstetrician_id: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          doula_present_id?: string
          obstetric_nurse_present_id?: string
          birth_observations?: string
          birth_preparation_course: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy: string
          breastfeeding_workshop: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring: string
          mother_age_at_birth?: number
          is_removed?: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          removal_gestational_age_weeks?: number
          removal_gestational_age_days?: number
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          birth_date?: string
          delivery_type?: string
          maternity?: string
          maternity_id?: string
          baby_name?: string
          baby_gender?: string
          birth_gestational_age_weeks?: number
          birth_gestational_age_days?: number
          full_name?: string
          patient_birth_date?: string
          estimated_due_date?: string
          registration_date?: string
          registration_gestational_age_weeks?: number
          registration_gestational_age_days?: number
          preferred_delivery_type?: string
          obstetrician_id?: string
          pediatrician_id?: string
          doula_id?: string
          obstetric_nurse_id?: string
          nutritionist_id?: string
          lactation_consultant_id?: string
          pelvic_physiotherapist_id?: string
          doula_present_id?: string
          obstetric_nurse_present_id?: string
          birth_observations?: string
          birth_preparation_course?: string
          birth_preparation_date?: string
          birth_preparation_status?: string
          newborn_care_course?: string
          newborn_care_date?: string
          newborn_care_status?: string
          pelvic_physiotherapy?: string
          breastfeeding_workshop?: string
          breastfeeding_workshop_date?: string
          breastfeeding_workshop_status?: string
          pediatric_consultation?: string
          pediatric_consultation_date?: string
          pediatric_consultation_status?: string
          nutritional_monitoring?: string
          mother_age_at_birth?: number
          is_removed?: boolean
          removed_at?: string
          removed_by?: string
          removal_reason?: string
          removal_gestational_age_weeks?: number
          removal_gestational_age_days?: number
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}